CREATE TABLE VEHICLE(
ID CHAR(7),
BRAND VARCHAR(50),
OWNER_FIRST_NAME VARCHAR(50),
OWNER_LAST_NAME VARCHAR(50),
PRIMARY KEY(ID)
);

CREATE TABLE MEASUREMENTS(
ROUTE_ID CHAR(5),
VEHICLE_ID CHAR(7),
MEASUREMENT_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
COOL_TEMP INT,
MAF_PRESSURE INT,
RPM INT,
SPEED INT,
THROTTLE INT,
LAT DOUBLE(11,8),
LON DOUBLE(11,8),
PRIMARY KEY(VEHICLE_ID, MEASUREMENT_DATE_TIME,ROUTE_ID),
FOREIGN KEY(VEHICLE_ID) REFERENCES VEHICLE(ID),
CONSTRAINT CHK_COOL_TEMP CHECK (COOL_TEMP>-20 AND COOL_TEMP<200),
CONSTRAINT CHK_MAF_PRESSURE CHECK (MAF_PRESSURE>0),
CONSTRAINT CHK_RPM CHECK (RPM>0),
CONSTRAINT CHK_SPEED CHECK (SPEED>0)
);